[theme]
base = "dark"
# primaryColor = "#FF4B4B"
# backgroundColor = "#1E1E1E"
# secondaryBackgroundColor = "#2C2F33"
# textColor = "#F5F5F5"
# font = "sans serif"



[client]
showSidebarNavigation = true
showErrorDetails = true
caching = true



[layout]
wide = true

[runner]
fastReruns = true
magicEnabled = true


[server]
runOnSave = true
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
